image:
  name: scrmhub/php55-awscli:1.1
  username: $DOCKER_USERNAME
  password: $DOCKER_PASSWORD
  email: $DOCKER_EMAIL

pipelines:
  branches:
    develop: # run tests
            - step:
                script:
                  - apt-get update && apt-get install -y unzip
                  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                  - composer install
                  - vendor/bin/phpunit -c tests/phpunit.xml

    release/*: # run tests
        - step:
            script:
              - apt-get update && apt-get install -y unzip
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install
              - vendor/bin/phpunit -c tests/phpunit.xml

    master: # run tests and push to packagist
        - step:
            script:
              - apt-get update && apt-get install -y unzip
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install
              - vendor/bin/phpunit -c tests/phpunit.xml
              # push to Packagist
              - curl -XPOST -H'content-type:application/json' "https://packagist.org/api/update-package?username=accounts@scrmhub.com&apiToken=${PACKAGIST_API_TOKEN}" -d'{"repository":{"url":"https://bitbucket.org/scrmhub/php-sdk"}}'